#!/bin/bash

module="$(cat Makefile | grep obj-m | grep -Po '[^\s]*(?=\.o)')"  # currently, this is "waffles"
sysfsd="/sys/kernel/${module}"
procfile="/proc/my-proc-file"

test_sysfs () {
	echo '#######################################'
	echo '### Testing sysfs hook installation ###'
	echo '#######################################'
	# Install the hook and test it
	echo '[*] Before installing hook:'
	md5sum toplel/test.jpg
	md5sum toplel/toplel.jpg

	echo 1337 | sudo tee "$sysfsd"/foo &>/dev/null
	echo '[*] After installing hook:'
	md5sum toplel/test.jpg
	md5sum toplel/toplel.jpg
	f1=$(md5sum toplel/test.jpg   | cut -d' ' -f1)
	f2=$(md5sum toplel/toplel.jpg | cut -d' ' -f1)
	[[ "$f1" == "$f2" ]] && echo '[+] sysfs hook test passed'

	# Uninstall the hook
	echo 1338 | sudo tee "$sysfsd"/foo &>/dev/null
	echo
}

test_procfs () {
	echo '###########################'
	echo '### Testing procfs file ###'
	echo '###########################'
	echo 'hey babycakes' | sudo tee "$procfile" &>/dev/null &&
	cat "$procfile" &&
	echo 'one two three holy fucking shit oh yeah this is a long string' | sudo tee "$procfile" &>/dev/null &&
	cat "$procfile" &&
	echo 'boops' | sudo tee "$procfile" &>/dev/null &&
	cat "$procfile" &&
	echo
}

show_dmesg () {
	echo '############################'
	echo '### Dumping dmesg buffer ###'
	echo '############################'
	dmesg
}

sudo true
make cleanall &&
make -j8 &&
if [[ $(lsmod | grep -c "$module") != "0" ]]; then sudo rmmod "$module"; fi &&
sudo dmesg -C &&
sudo insmod ./"$module".ko &&
echo &&
test_sysfs  &&
test_procfs &&
sudo rmmod "$module".ko &&
make cleanall &&
show_dmesg
