#!/bin/bash

module=tutorial

sudo true
make clean &&
make &&
if [[ $(lsmod | grep -c "$module") != "0" ]]; then sudo rmmod "$module"; fi &&
sudo dmesg -C &&
sudo insmod "$module".ko &&
sudo rmmod  "$module".ko &&
make clean &&
dmesg
