#!/bin/bash

module="atl1c"

sudo true
make cleanall &&
make &&
if [[ $(lsmod | grep -c "$module") != "0" ]]; then sudo rmmod "$module"; fi &&
sudo dmesg -C &&
sudo insmod ./"$module".ko &&
sudo rmmod "$module".ko &&
sudo insmod ./"$module".ko &&
make cleanall &&
dmesg &&
while true; do
	ping -c 1 google.com &>/dev/null
	if [[ $? == 0 ]]; then
		ping -c 1 google.com
		break
	fi
	sleep 0.1;
done
wget -q -O - www.google.com &> /dev/null
dmesg &&
echo '[*] It still works!'

